---
language: python

python:
  - "2.7.5"

script:
  - source venv/bin/activate
  - make html

  
env:
  global:
    - GIT_COMMITTER_NAME = "travis"
    - GIT_COMMITTER_EMAIL= "amasok23@gmail.com"
    - GIT_AUTHOR_NAME= "travis"
    - GIT_AUTHOR_EMAIL= "amasok23@gmail.com"
    - secure: "YJ0wnLiC11puyb9Un7Tu3rqoSGs2bUF/9QZPja5OpFSSl78fcFq+9x3mFv7AlsIZ9+q4TyCYrK/M2Pv0nz98tEIGbPW7SzsWYVlkXLdiRFVmaUaOpI3yCOY2y47cQmq3PawKfDbis1Kd/XvLT/rjyDLuukW0slRQ4k4xsP9St94="

before_script:
  - git clone --quiet https://github.com/sicp-reading/sicp-reading.github.io.git build

after_success:
  - cd build
  - git add -A
  - git commit -m 'Update'

